### ISSUE TITLE
Appending dropping first word.

### ISSUE THREAD

**Issue by cadooo** [gopatrik/ajour#2]
Using -t The first word is being dropped. So "ajour -t Quick Brown Fox" results in "ajour.md << Brown Fox".

It looks like the issue is that the first word is part of argv.t and the rest is in argv._. If I do 'ajour -t test' or 'ajour -t "This is a test" it outputs Error: no message specified.

I am using windows and CYGWIN.

**Comment by gopatrik** [comment]
Oh, try putting the -t flag last. i.e. `$ ajour Quick Brown Fox -t`. Let me know if it works out! My understanding is that in bash, when you put something after a flag it is sent as an argument _to the flag_. But if the flag is put last, it becomes a boolean value.

Closing issue.
