### ISSUE TITLE
Difference to Hexo

### ISSUE THREAD

**Issue by miloskroulik** [gopatrik/ajour#6]
Well, I know, that Hexo is supposed to be static blog generator, but I think, it can fulfill ajour use case as well (well, I don't know how to append notes in Hexo, yet). I'm probably missing something, can you enlighten me, please?

**Comment by derryl** [comment]
This doesn't appear to be a site generator -- it's just a tool for quickly adding notes to a single Markdown file.

**Comment by miloskroulik** [comment]
You're right, I missed the fact, that it's working with single markdown file.
